// react-app/src/dashboard/dashboard.tsx
import "./dashboard.css";
import { useEffect, useState } from "react";
import axios from "axios";
import Card from "../card/card.tsx";

interface DashboardProps {
  dataSet?: 1000 | 10_000 | 100_000 | 1_000_000;
}

export interface Person {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  gender: "Male" | "Female" | "Genderqueer";
  avatar: string;
  balance: string;
}

const Dashboard: React.FC<DashboardProps> = ({ dataSet = 1000 }) => {
  const [data, setData] = useState<Person[]>([]);
  const [filteredData, setFilteredData] = useState<Person[]>([]);
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [debouncedSearchTerm, setDebouncedSearchTerm] = useState<string>("");

  const fetchData = async (size: 1000 | 10_000 | 100_000 | 1_000_000) => {
    let result;
    if (size === 1000) result = await axios.get("/MOCK_DATA.json").then((res) => res.data);
    else if (size === 10_000) result = await axios.get("/MOCK_DATA_10_000.json").then((res) => res.data);
    else if (size === 100_000) result = await axios.get("/MOCK_DATA_100_000.json").then((res) => res.data);
    else if (size === 1_000_000) result = await axios.get("/MOCK_DATA_1_000_000.json").then((res) => res.data);
    setData(result);
  };

  useEffect(() => {
    fetchData(dataSet).then();
  }, [dataSet]);

  useEffect(() => {
    const handler = setTimeout(() => {
      setDebouncedSearchTerm(searchTerm);
    }, 300);

    return () => {
      clearTimeout(handler);
    };
  }, [searchTerm]);

  useEffect(() => {
    const filtered = data.filter((person) =>
      (person.first_name + person.last_name + person.email + person.gender + person.id)
        .toLowerCase()
        .includes(debouncedSearchTerm.toLowerCase().replace(" ", ""))
    );
    setFilteredData(filtered.slice(0, 100));
  }, [data, debouncedSearchTerm]);

  return (
    <div className="dashboard">
      <input
        type="text"
        className="searchTerm"
        placeholder="search..."
        onChange={(e) => setSearchTerm(e.target.value)}
      />
      <ul>
        {filteredData.map((person) => (
          <li key={person.id}>
            <Card person={person} />
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Dashboard;

// vue-app/src/components/Dashboard.vue
<script setup>
import Card from "@/components/Card.vue";
import {computed, onMounted, ref, watch} from "vue";
import axios from "axios";

const props = defineProps(['dataSet'])
const data = ref([]);
const searchTerm = ref('');
const debouncedSearchTerm = ref('');

const filteredData = computed(() => {
  return data.value
    .filter((person) =>
      (person.first_name + person.last_name + person.email + person.gender + person.id)
        .toLowerCase()
        .includes(debouncedSearchTerm.value.toLowerCase().replaceAll(' ', ''))
    )
    .slice(0, 100);
});

watch(searchTerm, (newTerm) => {
  clearTimeout(debouncedSearchTerm.timeout);
  debouncedSearchTerm.timeout = setTimeout(() => {
    debouncedSearchTerm.value = newTerm;
  }, 300);
});

const fetchData = async (size) => {
  let result;
  if (size === 1000) result = await axios.get("/MOCK_DATA.json").then((res) => res.data);
  else if (size === 10_000) result = await axios.get("/MOCK_DATA_10_000.json").then((res) => res.data);
  else if (size === 100_000) result = await axios.get("/MOCK_DATA_100_000.json").then((res) => res.data);
  else if (size === 1_000_000) result = await axios.get("/MOCK_DATA_1_000_000.json").then((res) => res.data);  // Manuell JSON parsen
  data.value = result;
};

onMounted(() => fetchData(props.dataSet))
</script>

<template>
  <div class="dashboard">
    <input
      type="text"
      class="searchTerm"
      placeholder="search..."
      v-model="searchTerm"
    />
    <ul>
      <li v-for="person in filteredData" :key="person.id">
        <Card :person="person" />
      </li>
    </ul>
  </div>
</template>

<style scoped>
.dashboard {
  display: block;
  max-width: 80em;
  margin: auto;
}

ul {
  list-style-type: none;
  padding: 0;
}

</style>
