// src/app/card/card.component.ts
import {Component, Input} from '@angular/core';
import {Person} from '../data-service/data.service';
import {CurrencyPipe, NgOptimizedImage} from '@angular/common';

@Component({
  selector: 'app-card',
  imports: [
    NgOptimizedImage
  ],
  templateUrl: './card.component.html',
  styleUrl: './card.component.css'
})
export class CardComponent {
  @Input({required: true}) person!: Person;
}

@switch (person.gender) {
  @case("Male") {
    <img ngSrc="profileIconMale.png?name={{person.id}}" alt="{{ person.first_name }} {{person.last_name}} Avatar" width="256" height="256">
  }
  @case("Female") {
    <img ngSrc="profileIconFemale.png?name={{person.id}}" alt="{{ person.first_name }} {{person.last_name}} Avatar" width="256" height="256">
  }
  @default {
    <img ngSrc="profileIconDefault.png?name={{person.id}}" alt="{{ person.first_name }} {{person.last_name}} Avatar" width="256" height="256">
  }
}
<div class="person-info">
  <p><strong>{{ person.first_name }} {{person.last_name}}</strong></p>
  <p>{{ person.email }}</p>
  <p>{{ person.gender }}</p>
  <p class="balance">{{ person.balance }}</p>
</div>

// react-app/src/card/card.tsx
import './Card.css';
import {Person} from "../dashboard/dashboard.tsx";
import * as React from "react";


interface CardProps {
  person: Person;
}

const Card: React.FC<CardProps> = ({ person }) => {
  const getImageSrc = () => {
    switch (person.gender) {
      case "Male":
        return `profileIconMale.png?name=${person.id}`;
      case "Female":
        return `profileIconFemale.png?name=${person.id}`;
      default:
        return `profileIconDefault.png?name=${person.id}`;
    }
  };

  return (
    <div className="card">
      <img src={getImageSrc()} alt={`${person.first_name} ${person.last_name} Avatar`} width="256" height="256" />
      <div id={`person_${person.id}`} className="person-info">
        <p><strong>{person.id}: {person.first_name} {person.last_name}</strong></p>
        <p>{person.email}</p>
        <p>{person.gender}</p>
        <p className="balance">{person.balance}</p>
      </div>
    </div>
  );
};

export default Card;
